apiVersion: v1
kind: Service
metadata:
  name: auth-server
  namespace: production
  labels:
    app: auth-server
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: auth-server